make TX fee as a reward
chain4travel/coreth pull request #3
Opened 2022-07-22 12:10 UTC by 11Yupi11

Create wallet to accumulate TX fees. Add some logic to split all TX fee and to burn only 70% of it, but others 30% send directly to the accumulative wallet

2022-07-25 07:21 UTC, DerTiedemann commented
Looks good so far, not sure if we need a sunrise phase here, e.g. we could use the already existing SunrisePhase0 or just leave it as it is. But as a thing that would be needed is to add the accululation address to the genesis block.

2022-07-26 14:21 UTC, 11Yupi11 commented
I have added all logic to take and work with Accumulative address from genesis file

2022-08-30 11:51 UTC, evlekht requested changes

2022-08-30 11:51 UTC, evlekht commented on core/state_transition.go
> +	exportedPartFee := new(big.Int).Mul(onePercentCalc, new(big.Int).SetUint64(60))
You should multiply things first before you divide them in such big.Int calculations - that way you will lose less precision.

2022-10-21 08:56 UTC, peak3d commented
Replaced by #15 and ongoing development of @pnowosie

2022-10-21 08:56 UTC, closed without merging