Fee reward collection on the C-chain
chain4travel/coreth pull request #46
Opened 2022-11-21 13:57 UTC by pnowosie

This PR implements collection of the rewards from the burned fees. 
**It does not import exported funds into P-chain**. It needs to be done in separate PR.
Solution draft is posted in [TECH-273](https://c4t.atlassian.net/browse/TECH-273)

It extends the genesis and the Block's header of these parameters:

- `FeeRewardMinAmountToExport uint64` - expressed in the P/X-chain precision, minimum amount that needs to be reached to issue the CollectRewardTx
- `FeeRewardRate uint64` - percent of the fees exported as Validator rewards. It is denominated to uint64 from floating point ratio (`ratio * evm.percentDenominator`). E.g. 30% will be expressed as `0.30 * 1_000_000 == 300_000`
- `IncentivePoolRewardRate` - percent of the fees transferred to DApps Incentive Pool. It is denominated to uint64 from floating point ratio (`ratio * evm.percentDenominator`). See 👆. 
- `FeeRewardExportAddress (HEX) string` - P-Chain address bytes as hex to export Validator rewards to
- `IncentivePoolRewardAddress (HEX) string` - IP Contract address (`0x010000000000000000000000000000000000000c`)

This parameters for now are constants - see: [0d4877d](https://github.com/chain4travel/caminoethvm/blob/0d4877d0dea240909855067f319135c17c3f87c6/plugin/evm/collect_rewards_tx.go#L35-L43)

Also make sure the `Sunrise0Phase` is active (set `\"sunrisePhase0BlockTimestamp\":0` in the genesis "config").
SunrisePhase0 is important to set `BlockGasCost` to `0` which **allows the `CollectRewardsTx` to pay no fees**.s

### Testing instructions
- Fund the C-chain account
- Make a transfer (repeat)
- Once the calculated rewards exceeds the minimum amount you shall see the additional block is mined. This block will contain `CollectRewardsTx`.
- Observe that BH (coinbase) address balance has been decreased,
- Check that balance of the DApp's IP contract has been increased,
- Check that new UTXO appeared for `FeeRewardExportAddress` on the P-chain, you can import it via RPC if you set your account address as `FeeRewardExportAddress`.

This truffle's [testing script](https://gist.github.com/pnowosie/b5b32a6bb5acf537e27d46abcc343200) might be handy.

Estimation of the transfer fees depends on the frequency of the transfer Txs - more frequent the more expensive fees.

2023-01-17 11:44 UTC, c4t-ag requested changes

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/camino_block_fee_collection.go
> +//
This is NOT derived code, please 2 line License

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/camino_block_fee_collection.go
> +	if err == nil {
I suggest to code in common style `if err != nil {return}`

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/camino_block_fee_collection.go
> +	validatorRewards := state.GetState(header.Coinbase, Slot1).Big()
Do we really need 2 slots in coinbase? IMO coinbase only needs so know the balance last time fees were fetched.

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/camino_block_fee_collection.go
> +func (b *Block) createReawardsCollectionTx(calculation *RewardCalculation) (*Tx, error) {
Typo

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/camino_block_fee_collection.go
> +	tx, err := b.vm.NewCollectRewardsTx(
What is "Collection"

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/collect_rewards_tx.go
> +	avax.Metadata
Isn't there a "BaseTx" base class on c-chain ?

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/collect_rewards_tx.go
> +	Coinbase                   common.Address `serialize:"true" json:"coinbase"`
Why do we have these 3 entries inside a TX?

2023-01-17 11:44 UTC, c4t-ag commented on plugin/evm/collect_rewards_tx.go
> +	// 1. Redo the calculation and compare the results
I doubt that this will work, you dont know in beforehand (when building the TX)  at what timeStamp / block the TX will be executed.

2023-01-17 12:18 UTC, c4t-ag commented on plugin/evm/reward_calculator.go
> +	if rc.ValidatorRewardToExport == 0 ||
IMO the most important thing is missing: check that the weight between the 2 amounts is correct.

2023-01-17 12:25 UTC, c4t-ag commented on plugin/evm/collect_rewards_tx.go
> +	feeRewardExportAddrId, err := ids.ToShortID(FeeRewardExportAddress.Bytes())
Do you really need FeeRewardExportAddress except for converting all over the time?
Maybe make once a buffer.

2023-01-17 13:15 UTC, pnowosie commented on plugin/evm/camino_block_fee_collection.go
> +	tx, err := b.vm.NewCollectRewardsTx(
It was meant as "Tx is collecting the rewards"

2023-01-17 13:26 UTC, pnowosie commented on plugin/evm/camino_block_fee_collection.go
> +	validatorRewards := state.GetState(header.Coinbase, Slot1).Big()
Correct, we don't need two if we assume that validator reward ratio is the same as Incentive Pool one. The code is more generic and allows different ratios

https://github.com/chain4travel/caminoethvm/blob/37720ca56b1cad0cff03a57c4b78ef7b391ba66d/plugin/evm/collect_rewards_tx.go#L41-L42

2023-01-17 13:45 UTC, pnowosie commented on plugin/evm/collect_rewards_tx.go
> +	Coinbase                   common.Address `serialize:"true" json:"coinbase"`
I've removed the later two and use variables instead.
Regarding the `Coinbase` it comes from the block header and which I cannot easily access here in EVMStateTransfer
https://github.com/chain4travel/caminoethvm/blob/37720ca56b1cad0cff03a57c4b78ef7b391ba66d/plugin/evm/collect_rewards_tx.go#L294

2023-01-17 13:54 UTC, pnowosie commented on plugin/evm/collect_rewards_tx.go
> +	// 1. Redo the calculation and compare the results
What is actually done here it is repeated the calculation on the data when the Tx was created.
Tx contains all the parameters the reward was calculated from as well as the results, here I'm comparing the computation.

2023-01-17 14:29 UTC, pnowosie commented on plugin/evm/reward_calculator.go
> +	if rc.ValidatorRewardToExport == 0 ||
Do you mean this `rc.ValidatorRewardAmount == rc.IncentivePoolRewardAmount`?

2023-01-20 10:13 UTC, pnowosie commented on plugin/evm/collect_rewards_tx.go
> +	IncentivePoolRewardAddressStr = "0x010000000000000000000000000000000000000c"
One of these should be different?

2023-02-01 08:01 UTC, pnowosie commented
Cleaned code from this PR was merge in https://github.com/chain4travel/caminoethvm/pull/57

2023-02-01 08:01 UTC, closed without merging