Add Guard clause against contract creation from non verified Adresses and not execute function that are blacklisted
chain4travel/coreth pull request #48
Opened 2022-11-30 12:34 UTC by DerTiedemann

- Enable admin enforcement
- Make all backends aware of the change && enable on main backend
- Fix old tests
- enforcement tests

This PR introduces a simple guard clause inside of the CREATE instruction that checks if the caller address has the KYC flag set in the precompiled contract at `0x010000000000000000000000000000000000000a`. This SC is deployed as one of the precompiled SCs.

Furthermore I added the test ethaddress (the one thats funded) to be the admin for this admin contract to be able to add/remove roles for address for testing.
Now when an address thats not verified tries to create a contract:

- The initial test will fail and return an error
- if that error is ignored the TX will fail

Also a Blacklist is introduced that will make any tx fail that in any way or form call a function in that list.
Everywhere were the NativeAssetCall is blocked by avax i added a check if the function signature is present in the admin contract and return an error.
Currently this only causes the TX to fail, e.g. it costs gas and does not revert.

For easier testing, this whole behavior is controlled by a new value in the vm.Config struct called EnableAdminEnforcement. This allowes the VM to act like normal and do not break test. Be aware that this has to be turned on explicitly.

All the revelant places have been updated to be aware of the changes and the chain will boot with enforcement enabled.

2022-12-23 10:09 UTC, c4t-ag requested changes
Needs clarification before continuing / fixing

2022-12-23 10:09 UTC, c4t-ag commented on accounts/abi/bind/backends/simulated.go
> +func NewSimulatedBackendWithDatabaseAndValidKYCRole(database ethdb.Database, alloc core.GenesisAlloc, gasLimit uint64, addr common.Address) *SimulatedBackend {
They should go in its own camino_simulated.go file.
Side node: If we change foreign code we adjust license header

2022-12-23 10:09 UTC, c4t-ag commented on core/admin/admin_interface.go
> +package admin
License Header

2022-12-23 10:09 UTC, c4t-ag commented on core/admin/admin_interface_test.go
> +package admin_test
License header

2023-03-22 17:13 UTC, pnowosie commented on core/admin/admin_interface.go
> +	return crypto.Keccak256Hash(append(addr.Hash().Bytes(), common.HexToHash("0x2").Bytes()... /*slot 2 reference admin.sol map(address => uint)*/))
```suggestion
	return crypto.Keccak256Hash(addr.Hash().Bytes(), common.HexToHash("0x2").Bytes()/*slot 2 reference admin.sol map(address => uint)*/)
```
you can drop `append` which leads the same result

2023-10-04 08:13 UTC, DerTiedemann commented
Implemented by the Admin controller

2023-10-04 08:13 UTC, closed without merging