Add ability to change Base fee manually
chain4travel/coreth pull request #6
Opened 2022-08-29 06:51 UTC by 11Yupi11

**General:**  logic of getting reward of every transaction left here (the address reused for new feature too)

**Main changes:** 

- SunrisePhase0 constant of base fee was deleted
- To stateDB new StateObject was added on the specific address (the same as Accumulative address, as it is stored in every block and easy to get it in all parts of the transaction)
- Added function to read information from stateDB
- Added function to change StateObject to the new value
- To change the Base Fee you need to send transaction from C-chain address of C4T account to the same address and set in value the ammount of BaseFee you want in nanoCAM, but for now it might not be more than 0.000000225

**What need to be done:**

- Clean the code and make it better
- Fix the tests

2022-08-29 12:39 UTC, DerTiedemann commented
I would love to have the basefee change functionality and the accumulative address to be in seperate PR so its easier to write test for them. Also we should figure out what test we need to fix and which we can ignore for now.

2022-08-29 12:43 UTC, DerTiedemann requested changes
This pr is a little broken and needs a lot of cleanup.
Id suggest we split them into two and work on the two features seperatly.
E.g. one to add a superuser/accumulative address we can use to save the part of the basefee to send to validators. And another one to facilitate the basefee change.

2022-08-29 12:43 UTC, DerTiedemann commented on consensus/consensus.go
> +
Id recommend to extract this into an seperate interface instead of using the existing one.
Just for clarity.

2022-08-29 12:43 UTC, DerTiedemann commented on core/state/state_object.go
> +		otherBaseFee := db.GetBaseFee(common.HexToAddress("0x36d86bb280b4e088793a60c781c7edcd9fa33255"))
This needs to be extracted to a seperate address in genesis or just use the accumualtive address.
If so, lets rename it to root or superuser address.

2022-08-29 12:43 UTC, DerTiedemann commented on core/state/statedb.go
> +	return big.NewInt(225_000_000_000)
This needs to be configurable e.g. in genesis or use the baseline sunrise phae value

2022-08-29 12:43 UTC, DerTiedemann commented on core/state_transition.go
> +	if st.msg.From() == common.HexToAddress("0xc02104f25e07f827195cebf032a1d7bfecf0cb7c") && *st.msg.To() == common.HexToAddress("0xc02104f25e07f827195cebf032a1d7bfecf0cb7c") {
Use configurable address here.

2022-08-29 12:58 UTC, 11Yupi11 commented on core/state/state_object.go
> +		otherBaseFee := db.GetBaseFee(common.HexToAddress("0x36d86bb280b4e088793a60c781c7edcd9fa33255"))
It is Accumulative address.....i can't get it from this directory

2022-08-29 12:59 UTC, 11Yupi11 commented on core/state_transition.go
> +	if st.msg.From() == common.HexToAddress("0xc02104f25e07f827195cebf032a1d7bfecf0cb7c") && *st.msg.To() == common.HexToAddress("0xc02104f25e07f827195cebf032a1d7bfecf0cb7c") {
I want to ask if it is a good idea just to add specific address like "C4Taddress" to genesis file to use it.

2022-08-31 13:58 UTC, DerTiedemann commented
Can you have a look at the failing build and have a go at fixing it, seems like some parts were not updated to som function siganture check

2022-09-04 16:08 UTC, c4t-ag requested changes
This PR needs a discussion about the concept and clarifications about change of existing behaviour. We should look for a solution with less invasive changes b.t.w.
Beside this this PR has to be cleaned up, and CI (linter issues) should be fixed, but pls. wait with that until we discussed the other topics.

2022-09-04 16:08 UTC, c4t-ag commented on core/vm/evm.go
> +	C4Taddress  common.Address // Provides information for C4Taddress
Why do we need a new field in such a general structure?

2022-09-04 16:08 UTC, c4t-ag commented on core/state_transition.go
> +	if st.msg.From() == st.evm.Context.C4Taddress && *st.msg.To() == st.evm.Context.C4Taddress {
For me this feels quite hacky.
Beside this To() can return nil if I'm not wrong which will kill e.g. contract creations.

2022-09-04 16:08 UTC, c4t-ag commented on core/state_transition.go
> +		if st.msg.Value().Cmp(big.NewInt(params.ApricotPhase3InitialBaseFee)) <= 0 {
Why do we have to deal with ApricotPhase3 here?

2022-09-04 16:08 UTC, c4t-ag commented on core/tx_pool.go
> +	_, baseFeeEstimate, err := dummy.EstimateNextBaseFee(pool.chainconfig, pool.currentHead, pool.currentState, uint64(time.Now().Unix()))
Is it really required to pass state here? In estimate... we already query state if I'm not wrong.

2022-09-04 16:08 UTC, c4t-ag commented on eth/gasprice/gasprice.go
> -		baseFee = new(big.Int).SetUint64(params.SunrisePhase0BaseFee)
This was introduced to make MetaMask happy, why is it reverted?

2022-09-04 16:08 UTC, c4t-ag commented on consensus/dummy/dynamic_fees.go
> +		return []byte{}, parent.BaseFee, nil
This kills the Sunrise definition, that changes should apply earliest after the first block in the new Phase.

2022-09-04 16:08 UTC, c4t-ag commented on core/types/state_account.go
> +	BaseFee     *big.Int
If I'm not wrong this is the wrong place for a "BaseFee"

2022-10-21 08:57 UTC, peak3d commented
Replaced by #15

2022-10-21 08:57 UTC, closed without merging