add new contract for MSig definition storage
chain4travel/coreth pull request #63
Opened 2023-03-23 12:13 UTC by pnowosie

MultiSig Smart Contract for definition storage PreDeploy addition.

Changes made:

- multisig.sol addition
- MultiSig.abi and multisig.go added for external calls of MultiSig API.
- Necessary changes in genesis.go file have been made. A proxy contract have not been added for the MultisigData contract because it is a simple data storage contract that does not require any upgrades. Therefore, the MultisigData contract is being deployed directly as a GenesisAccount using its bytecode.

2023-03-28 07:18 UTC, pnowosie commented
👍 Looks good to me!

2023-04-03 20:13 UTC, c4t-ag requested changes

2023-04-03 20:13 UTC, c4t-ag commented on core/genesis.go
> +	implAddress = common.HexToAddress("0x010000000000000000000000000000000000000e")
We should also use proxy logic here!

2023-04-06 13:48 UTC, c4t-ag approved these changes

2023-04-06 13:50 UTC, merged