Evlekht/node
chain4travel/coreth pull request #77
Opened 2024-01-25 13:15 UTC by evlekht

## Why this should be merged

## How this works

## How this was tested

2024-02-02 11:26 UTC, knikos requested changes
Some missing changes that I have identified by reviewing the introduced changes when caminogo was added as a submodule: (see https://github.com/chain4travel/caminoethvm/pull/49/commits/e89c2d89babefb74bbe0245b91727ba303754e8c#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188)
- revert changes on `.github/workflows/ci.yml` and `.github/workflows/e2e.yml`  related to git submodule. 
- revert change on `.golangci.yml` comparing to the commit above
- revert changes on scripts `build.sh`, `build_test.sh`, `build.sh` and `scripts/lint.sh`

2024-02-05 13:19 UTC, knikos submitted a review, later dismissed

2024-02-05 13:32 UTC, mo-c4t reviewed
workflows look good, but now CI will run for every PR, I recommend set PR branches to dev and chain4travel. Also E2E workflow won't run at all because of the On condition which ignores all branches.

2024-02-05 13:45 UTC, evlekht commented
> workflows look good, but now CI will run for every PR, I recommend set PR branches to dev and chain4travel. Also E2E workflow won't run at all because of the On condition which ignores all branches.

Those lines are unchanged, but its reasonable to limit ci to dev and c4t branches, I'll change it. E2E was disabled by Markus long time ago, I guess we just didnt want to deal with setting them up with caminogo instead of avalanchego, dunno. Lets leave it like it was for now

2024-02-05 13:58 UTC, mo-c4t approved these changes

2024-02-05 14:04 UTC, merged